// Generated by CoffeeScript 1.6.2
(function() {
  var answerbox, answertext, button, dragtargets, field1, field2;

  answerbox = jQuery('#answerbox');

  answertext = jQuery('#answertext');

  field1 = jQuery('#field1');

  field2 = jQuery('#field2');

  button = jQuery('#button');

  dragtargets = jQuery('#draggable');

  jQuery(function() {
    return jQuery(document).ready(function() {
      var flickraddress;
      jQuery('#draggable').draggable({
        containment: 'parent'
      });
      flickraddress = "http://api.flickr.com/services/feeds/photos_public.gne?jsoncallback=?";
      jQuery.getJSON(flickraddress, {
        tags: "little wild horse canyon",
        tagmode: "any",
        format: "json"
      }).done(function(data) {
        var item, _i, _len, _ref, _results;
        _ref = data.items;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          _results.push((function(item) {
            return jQuery("<img/>").attr("src", item.media.m).attr("class", "rounded").appendTo("#flickrarea");
          })(item));
        }
        return _results;
      });
      return button.click(function(event) {
        var word1, word2;
        word1 = field1.val();
        word2 = field2.val();
        alert("Look at the box below!");
        return answertext.html("Knock knock.<br> Who is there? <br>" + word1 + ". <br>" + word1 + " who? <br>" + word1 + " " + word2 + ".");
      });
    });
  });

}).call(this);
